login:
    pattern:   /login
    defaults:  { _controller: CollectiveGovtBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
    defaults:  { _controller: CollectiveGovtBundle:Security:logout }

authed:
    pattern:   /authed
    defaults:  { _controller: CollectiveGovtBundle:Security:getAuthState }
    requirements:
      _method:  POST

CollectiveGovtBundle:
    resource: "@CollectiveGovtBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
